---
- name: Install full package Docker and Docker-Compose
  hosts: Web
  gather_facts: no

  tasks:
    - name: Update the apt package index
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install packages for apt add repository over HTTPS
      apt:
        name: "{{ packagesdep }}"
        force_apt_get: yes
        state: latest
        update_cache: yes
      vars:
        packagesdep:
        - git
        - apt-transport-https
        - ca-certificates
        - wget
        - software-properties-common
        - gnupg2
        - curl

    - name: Add Apt signing key from official docker repo
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: add docker official repository for Debian Stretch
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        state: present

    - name: Index new repo into the cache
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: actually install docker
      apt:
        name: "docker-ce"
        state: latest

    - name: copy and exectude script "docker-compose"
      script: /home/dima/ansible-deploy-docker/docker-compose.sh






#sudo mkdir /sys/fs/cgroup/systemd
#sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd